### ISSUE TITLE
Circular dependency error msg

### ISSUE THREAD

**Issue by Kolobok12309** [unjs/jiti#360]
### Environment

jiti: 2.4.2
node: v20.9.0

### Reproduction

https://codesandbox.io/p/sandbox/jiti-export-default-as-node-9ckx5x

### Describe the bug

After change version of @nuxt/kit to last (3.15.2) jiti updated from 1.x to 2.4.2 and out modules stopped loading with errors

First error
```
(0 , _nuxtUtils.getAliases) is not a function
```

After add `console.log` of another import error change to

```
Cannot read properties of undefined (reading 'default')                                                                                                               15:16:53

  at Object.get [as getDistPath]
```

Import of `getDistPath` looks like this `export { default as getDistPath } from './getDistPath';`, i think problem with specific export, try in clean playground, none

After some debug i find circular dependencies, but this error messages don't let me understand this

### Additional context

All worked fine with 1.21.6

### Logs

```sh

```
