### ISSUE TITLE
1.12.10 break nuxt compilation

### ISSUE THREAD

**Issue by daniluk4000** [unjs/jiti#54]
I use Nuxt Config as nuxt.config.ts, and after upgrade to 1.12.10 build started to fail with error Cannot find module nuxt.config

![изображение](https://user-images.githubusercontent.com/10450717/151007230-5d16d346-d6d7-46ec-96c0-a9da958d40f0.png)

Workaround: downgrade to Jiti 1.12.9 in package.json, if installed through package-lock/yarn.lock:

``` json
  "resolutions": {
    "jiti": "1.12.9"
  },
```

**Comment by danielroe** [comment]
see also https://github.com/nuxt/create-nuxt-app/issues/926

**Comment by pi0** [comment]
Thanks for reporting. Issue should be resolved in latest hotfix. Please try recreating lockfile.

**Comment by daniluk4000** [comment]
Can confirm as fixed in 1.12.13. Thanks for quick fix!
